[tasks.build]
toolchain = "nightly-x86_64-unknown-linux-gnu"
command = "cargo"
args = [
    "build",
    "--target",
    "riscv32imc-unknown-none-elf",
]

[tasks.doc]
toolchain = "nightly-x86_64-unknown-linux-gnu"
command = "cargo"
args = [
    "doc",
    "--target",
    "riscv32imc-unknown-none-elf",
]