[build]
target = "xtensa-esp32s2-espidf"

[target.xtensa-esp32s2-espidf]
linker = "ldproxy"
rustflags = ["-C", "default-linker-libraries"]

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]

[env]
# NOTE: there are some issues with ESP-IDF v4.3.1, so we will use master instead
ESP_IDF_VERSION = { value = "master" }
# NOTE: currently the `workspace` and `custom:<relative-path>` options are broken
# so I have hardcoded a path. We could also pass `out`, but that means the ESP-IDF
# is cleared any time `cargo clean` is run, and it takes a long time to re-download
# https://github.com/esp-rs/esp-idf-sys/issues/44
ESP_IDF_TOOLS_INSTALL_DIR = { value = "custom:/opt/rust-workspace/projects/esp32s2-workspace/.embuild", force = true }
ESP_IDF_SDKCONFIG_DEFAULTS = { value = "./sdkconfig.defaults", relative = true }