[tasks.flash]
workspace = false
command = "powershell.exe"
args = [
    "-Command",
    "espflash --speed 460800 COM5 ./target/xtensa-esp32s2-espidf/debug/main; espmonitor COM5",
]

[tasks.debug]
dependencies = [
    "build",
    "flash",
]
